name = "tlin_bot"
main = "src/index.ts"
node_compat = true
compatibility_date = "2022-12-03"

[triggers]
crons = [ "1 * * * *" ]

[vars]
MODE = "testing"
CHANNEL_ID_TESTING = "-1001240618367"
CHANNEL_ID = "-1001134153564"
TOKEN = "394348712:AAEbTNxjvMM4u7WCzOX3tTeAOC3i_tOh7dw"
